package team

import (
	"context"
	"fmt"
	"log/slog"
)

// TeamGameStreakFinderParams holds parameters for the TeamGameStreakFinder endpoint.
type TeamGameStreakFinderParams struct {
	ActiveStreaksOnlyNullable string
	ActiveTeamsOnlyNullable string
	BtrOppAstNullable string
	BtrOppBlkNullable string
	BtrOppDrebNullable string
	BtrOppFg3aNullable string
	BtrOppFg3mNullable string
	BtrOppFg3PctNullable string
	BtrOppFgaNullable string
	BtrOppFgmNullable string
	BtrOppFgPctNullable string
	BtrOppFtaNullable string
	BtrOppFtmNullable string
	BtrOppFtPctNullable string
	BtrOppOrebNullable string
	BtrOppPfNullable string
	BtrOppPtsNullable string
	BtrOppPts2ndChanceNullable string
	BtrOppPtsFbNullable string
	BtrOppPtsOffTovNullable string
	BtrOppPtsPaintNullable string
	BtrOppRebNullable string
	BtrOppStlNullable string
	BtrOppTovNullable string
	ConferenceNullable string
	DateFromNullable string
	DateToNullable string
	DivisionSimpleNullable string
	EqAstNullable string
	EqBlkNullable string
	EqDdNullable string
	EqDrebNullable string
	EqFg3aNullable string
	EqFg3mNullable string
	EqFg3PctNullable string
	EqFgaNullable string
	EqFgmNullable string
	EqFgPctNullable string
	EqFtaNullable string
	EqFtmNullable string
	EqFtPctNullable string
	EqMinutesNullable string
	EqOppPts2ndChanceNullable string
	EqOppPtsFbNullable string
	EqOppPtsOffTovNullable string
	EqOppPtsPaintNullable string
	EqOrebNullable string
	EqPfNullable string
	EqPtsNullable string
	EqPts2ndChanceNullable string
	EqPtsFbNullable string
	EqPtsOffTovNullable string
	EqPtsPaintNullable string
	EqRebNullable string
	EqStlNullable string
	EqTdNullable string
	EqTovNullable string
	GameIdNullable string
	GtAstNullable string
	GtBlkNullable string
	GtDdNullable string
	GtDrebNullable string
	GtFg3aNullable string
	GtFg3mNullable string
	GtFg3PctNullable string
	GtFgaNullable string
	GtFgmNullable string
	GtFgPctNullable string
	GtFtaNullable string
	GtFtmNullable string
	GtFtPctNullable string
	GtMinutesNullable string
	GtOppAstNullable string
	GtOppBlkNullable string
	GtOppDrebNullable string
	GtOppFg3aNullable string
	GtOppFg3mNullable string
	GtOppFg3PctNullable string
	GtOppFgaNullable string
	GtOppFgmNullable string
	GtOppFgPctNullable string
	GtOppFtaNullable string
	GtOppFtmNullable string
	GtOppFtPctNullable string
	GtOppOrebNullable string
	GtOppPfNullable string
	GtOppPtsNullable string
	GtOppPts2ndChanceNullable string
	GtOppPtsFbNullable string
	GtOppPtsOffTovNullable string
	GtOppPtsPaintNullable string
	GtOppRebNullable string
	GtOppStlNullable string
	GtOppTovNullable string
	GtOrebNullable string
	GtPfNullable string
	GtPtsNullable string
	GtPts2ndChanceNullable string
	GtPtsFbNullable string
	GtPtsOffTovNullable string
	GtPtsPaintNullable string
	GtRebNullable string
	GtStlNullable string
	GtTdNullable string
	GtTovNullable string
	LstreakNullable string
	LeagueIdNullable string
	LocationNullable string
	LtAstNullable string
	LtBlkNullable string
	LtDdNullable string
	LtDrebNullable string
	LtFg3aNullable string
	LtFg3mNullable string
	LtFg3PctNullable string
	LtFgaNullable string
	LtFgmNullable string
	LtFgPctNullable string
	LtFtaNullable string
	LtFtmNullable string
	LtFtPctNullable string
	LtMinutesNullable string
	LtOppAstNullable string
	LtOppBlkNullable string
	LtOppDrebNullable string
	LtOppFg3aNullable string
	LtOppFg3mNullable string
	LtOppFg3PctNullable string
	LtOppFgaNullable string
	LtOppFgmNullable string
	LtOppFgPctNullable string
	LtOppFtaNullable string
	LtOppFtmNullable string
	LtOppFtPctNullable string
	LtOppOrebNullable string
	LtOppPfNullable string
	LtOppPtsNullable string
	LtOppPts2ndChanceNullable string
	LtOppPtsFbNullable string
	LtOppPtsOffTovNullable string
	LtOppPtsPaintNullable string
	LtOppRebNullable string
	LtOppStlNullable string
	LtOppTovNullable string
	LtOrebNullable string
	LtPfNullable string
	LtPtsNullable string
	LtPts2ndChanceNullable string
	LtPtsFbNullable string
	LtPtsOffTovNullable string
	LtPtsPaintNullable string
	LtRebNullable string
	LtStlNullable string
	LtTdNullable string
	LtTovNullable string
	MinGamesNullable string
	OutcomeNullable string
	PoRoundNullable string
	SeasonNullable string
	SeasonSegmentNullable string
	SeasonTypeNullable string
	TeamIdNullable string
	VsConferenceNullable string
	VsDivisionNullable string
	VsTeamIdNullable string
	WstreakNullable string
	WrsOppAstNullable string
	WrsOppBlkNullable string
	WrsOppDrebNullable string
	WrsOppFg3aNullable string
	WrsOppFg3mNullable string
	WrsOppFg3PctNullable string
	WrsOppFgaNullable string
	WrsOppFgmNullable string
	WrsOppFgPctNullable string
	WrsOppFtaNullable string
	WrsOppFtmNullable string
	WrsOppFtPctNullable string
	WrsOppOrebNullable string
	WrsOppPfNullable string
	WrsOppPtsNullable string
	WrsOppPts2ndChanceNullable string
	WrsOppPtsFbNullable string
	WrsOppPtsOffTovNullable string
	WrsOppPtsPaintNullable string
	WrsOppRebNullable string
	WrsOppStlNullable string
	WrsOppTovNullable string
}

// GetTeamGameStreakFinder fetches data from the teamgamestreakfinder endpoint.
func (c *Client) GetTeamGameStreakFinder(ctx context.Context, params TeamGameStreakFinderParams) (*StatsResponse, error) {
	c.logger.InfoContext(ctx, "Fetching teamgamestreakfinder")

	reqParams := map[string]string{
		"ActiveStreaksOnly": params.ActiveStreaksOnlyNullable,
		"ActiveTeamsOnly": params.ActiveTeamsOnlyNullable,
		"BtrOPPAST": params.BtrOppAstNullable,
		"BtrOPPBLK": params.BtrOppBlkNullable,
		"BtrOPPDREB": params.BtrOppDrebNullable,
		"BtrOPPFG3A": params.BtrOppFg3aNullable,
		"BtrOPPFG3M": params.BtrOppFg3mNullable,
		"BtrOPPFG3PCT": params.BtrOppFg3PctNullable,
		"BtrOPPFGA": params.BtrOppFgaNullable,
		"BtrOPPFGM": params.BtrOppFgmNullable,
		"BtrOPPFG_PCT": params.BtrOppFgPctNullable,
		"BtrOPPFTA": params.BtrOppFtaNullable,
		"BtrOPPFTM": params.BtrOppFtmNullable,
		"BtrOPPFT_PCT": params.BtrOppFtPctNullable,
		"BtrOPPOREB": params.BtrOppOrebNullable,
		"BtrOPPPF": params.BtrOppPfNullable,
		"BtrOPPPTS": params.BtrOppPtsNullable,
		"BtrOPPPTS2NDCHANCE": params.BtrOppPts2ndChanceNullable,
		"BtrOPPPTSFB": params.BtrOppPtsFbNullable,
		"BtrOPPPTSOFFTOV": params.BtrOppPtsOffTovNullable,
		"BtrOPPPTSPAINT": params.BtrOppPtsPaintNullable,
		"BtrOPPREB": params.BtrOppRebNullable,
		"BtrOPPSTL": params.BtrOppStlNullable,
		"BtrOPPTOV": params.BtrOppTovNullable,
		"Conference": params.ConferenceNullable,
		"DateFrom": params.DateFromNullable,
		"DateTo": params.DateToNullable,
		"Division": params.DivisionSimpleNullable,
		"EqAST": params.EqAstNullable,
		"EqBLK": params.EqBlkNullable,
		"EqDD": params.EqDdNullable,
		"EqDREB": params.EqDrebNullable,
		"EqFG3A": params.EqFg3aNullable,
		"EqFG3M": params.EqFg3mNullable,
		"EqFG3_PCT": params.EqFg3PctNullable,
		"EqFGA": params.EqFgaNullable,
		"EqFGM": params.EqFgmNullable,
		"EqFG_PCT": params.EqFgPctNullable,
		"EqFTA": params.EqFtaNullable,
		"EqFTM": params.EqFtmNullable,
		"EqFT_PCT": params.EqFtPctNullable,
		"EqMINUTES": params.EqMinutesNullable,
		"EqOPPPTS2NDCHANCE": params.EqOppPts2ndChanceNullable,
		"EqOPPPTSFB": params.EqOppPtsFbNullable,
		"EqOPPPTSOFFTOV": params.EqOppPtsOffTovNullable,
		"EqOPPPTSPAINT": params.EqOppPtsPaintNullable,
		"EqOREB": params.EqOrebNullable,
		"EqPF": params.EqPfNullable,
		"EqPTS": params.EqPtsNullable,
		"EqPTS2NDCHANCE": params.EqPts2ndChanceNullable,
		"EqPTSFB": params.EqPtsFbNullable,
		"EqPTSOFFTOV": params.EqPtsOffTovNullable,
		"EqPTSPAINT": params.EqPtsPaintNullable,
		"EqREB": params.EqRebNullable,
		"EqSTL": params.EqStlNullable,
		"EqTD": params.EqTdNullable,
		"EqTOV": params.EqTovNullable,
		"GameID": params.GameIdNullable,
		"GtAST": params.GtAstNullable,
		"GtBLK": params.GtBlkNullable,
		"GtDD": params.GtDdNullable,
		"GtDREB": params.GtDrebNullable,
		"GtFG3A": params.GtFg3aNullable,
		"GtFG3M": params.GtFg3mNullable,
		"GtFG3_PCT": params.GtFg3PctNullable,
		"GtFGA": params.GtFgaNullable,
		"GtFGM": params.GtFgmNullable,
		"GtFG_PCT": params.GtFgPctNullable,
		"GtFTA": params.GtFtaNullable,
		"GtFTM": params.GtFtmNullable,
		"GtFT_PCT": params.GtFtPctNullable,
		"GtMINUTES": params.GtMinutesNullable,
		"GtOPPAST": params.GtOppAstNullable,
		"GtOPPBLK": params.GtOppBlkNullable,
		"GtOPPDREB": params.GtOppDrebNullable,
		"GtOPPFG3A": params.GtOppFg3aNullable,
		"GtOPPFG3M": params.GtOppFg3mNullable,
		"GtOPPFG3PCT": params.GtOppFg3PctNullable,
		"GtOPPFGA": params.GtOppFgaNullable,
		"GtOPPFGM": params.GtOppFgmNullable,
		"GtOPPFG_PCT": params.GtOppFgPctNullable,
		"GtOPPFTA": params.GtOppFtaNullable,
		"GtOPPFTM": params.GtOppFtmNullable,
		"GtOPPFT_PCT": params.GtOppFtPctNullable,
		"GtOPPOREB": params.GtOppOrebNullable,
		"GtOPPPF": params.GtOppPfNullable,
		"GtOPPPTS": params.GtOppPtsNullable,
		"GtOPPPTS2NDCHANCE": params.GtOppPts2ndChanceNullable,
		"GtOPPPTSFB": params.GtOppPtsFbNullable,
		"GtOPPPTSOFFTOV": params.GtOppPtsOffTovNullable,
		"GtOPPPTSPAINT": params.GtOppPtsPaintNullable,
		"GtOPPREB": params.GtOppRebNullable,
		"GtOPPSTL": params.GtOppStlNullable,
		"GtOPPTOV": params.GtOppTovNullable,
		"GtOREB": params.GtOrebNullable,
		"GtPF": params.GtPfNullable,
		"GtPTS": params.GtPtsNullable,
		"GtPTS2NDCHANCE": params.GtPts2ndChanceNullable,
		"GtPTSFB": params.GtPtsFbNullable,
		"GtPTSOFFTOV": params.GtPtsOffTovNullable,
		"GtPTSPAINT": params.GtPtsPaintNullable,
		"GtREB": params.GtRebNullable,
		"GtSTL": params.GtStlNullable,
		"GtTD": params.GtTdNullable,
		"GtTOV": params.GtTovNullable,
		"LStreak": params.LstreakNullable,
		"LeagueID": params.LeagueIdNullable,
		"Location": params.LocationNullable,
		"LtAST": params.LtAstNullable,
		"LtBLK": params.LtBlkNullable,
		"LtDD": params.LtDdNullable,
		"LtDREB": params.LtDrebNullable,
		"LtFG3A": params.LtFg3aNullable,
		"LtFG3M": params.LtFg3mNullable,
		"LtFG3_PCT": params.LtFg3PctNullable,
		"LtFGA": params.LtFgaNullable,
		"LtFGM": params.LtFgmNullable,
		"LtFG_PCT": params.LtFgPctNullable,
		"LtFTA": params.LtFtaNullable,
		"LtFTM": params.LtFtmNullable,
		"LtFT_PCT": params.LtFtPctNullable,
		"LtMINUTES": params.LtMinutesNullable,
		"LtOPPAST": params.LtOppAstNullable,
		"LtOPPBLK": params.LtOppBlkNullable,
		"LtOPPDREB": params.LtOppDrebNullable,
		"LtOPPFG3A": params.LtOppFg3aNullable,
		"LtOPPFG3M": params.LtOppFg3mNullable,
		"LtOPPFG3PCT": params.LtOppFg3PctNullable,
		"LtOPPFGA": params.LtOppFgaNullable,
		"LtOPPFGM": params.LtOppFgmNullable,
		"LtOPPFG_PCT": params.LtOppFgPctNullable,
		"LtOPPFTA": params.LtOppFtaNullable,
		"LtOPPFTM": params.LtOppFtmNullable,
		"LtOPPFT_PCT": params.LtOppFtPctNullable,
		"LtOPPOREB": params.LtOppOrebNullable,
		"LtOPPPF": params.LtOppPfNullable,
		"LtOPPPTS": params.LtOppPtsNullable,
		"LtOPPPTS2NDCHANCE": params.LtOppPts2ndChanceNullable,
		"LtOPPPTSFB": params.LtOppPtsFbNullable,
		"LtOPPPTSOFFTOV": params.LtOppPtsOffTovNullable,
		"LtOPPPTSPAINT": params.LtOppPtsPaintNullable,
		"LtOPPREB": params.LtOppRebNullable,
		"LtOPPSTL": params.LtOppStlNullable,
		"LtOPPTOV": params.LtOppTovNullable,
		"LtOREB": params.LtOrebNullable,
		"LtPF": params.LtPfNullable,
		"LtPTS": params.LtPtsNullable,
		"LtPTS2NDCHANCE": params.LtPts2ndChanceNullable,
		"LtPTSFB": params.LtPtsFbNullable,
		"LtPTSOFFTOV": params.LtPtsOffTovNullable,
		"LtPTSPAINT": params.LtPtsPaintNullable,
		"LtREB": params.LtRebNullable,
		"LtSTL": params.LtStlNullable,
		"LtTD": params.LtTdNullable,
		"LtTOV": params.LtTovNullable,
		"MinGames": params.MinGamesNullable,
		"Outcome": params.OutcomeNullable,
		"PORound": params.PoRoundNullable,
		"Season": params.SeasonNullable,
		"SeasonSegment": params.SeasonSegmentNullable,
		"SeasonType": params.SeasonTypeNullable,
		"TeamID": params.TeamIdNullable,
		"VsConference": params.VsConferenceNullable,
		"VsDivision": params.VsDivisionNullable,
		"VsTeamID": params.VsTeamIdNullable,
		"WStreak": params.WstreakNullable,
		"WrsOPPAST": params.WrsOppAstNullable,
		"WrsOPPBLK": params.WrsOppBlkNullable,
		"WrsOPPDREB": params.WrsOppDrebNullable,
		"WrsOPPFG3A": params.WrsOppFg3aNullable,
		"WrsOPPFG3M": params.WrsOppFg3mNullable,
		"WrsOPPFG3PCT": params.WrsOppFg3PctNullable,
		"WrsOPPFGA": params.WrsOppFgaNullable,
		"WrsOPPFGM": params.WrsOppFgmNullable,
		"WrsOPPFG_PCT": params.WrsOppFgPctNullable,
		"WrsOPPFTA": params.WrsOppFtaNullable,
		"WrsOPPFTM": params.WrsOppFtmNullable,
		"WrsOPPFT_PCT": params.WrsOppFtPctNullable,
		"WrsOPPOREB": params.WrsOppOrebNullable,
		"WrsOPPPF": params.WrsOppPfNullable,
		"WrsOPPPTS": params.WrsOppPtsNullable,
		"WrsOPPPTS2NDCHANCE": params.WrsOppPts2ndChanceNullable,
		"WrsOPPPTSFB": params.WrsOppPtsFbNullable,
		"WrsOPPPTSOFFTOV": params.WrsOppPtsOffTovNullable,
		"WrsOPPPTSPAINT": params.WrsOppPtsPaintNullable,
		"WrsOPPREB": params.WrsOppRebNullable,
		"WrsOPPSTL": params.WrsOppStlNullable,
		"WrsOPPTOV": params.WrsOppTovNullable,
	}

	resp, err := c.httpClient.SendRequest(ctx, "teamgamestreakfinder", reqParams)
	if err != nil {
		c.logger.ErrorContext(ctx, "Failed to fetch teamgamestreakfinder",
			slog.String("error", err.Error()))
		return nil, fmt.Errorf("failed to fetch teamgamestreakfinder: %w", err)
	}

	if !resp.IsValidJSON() {
		c.logger.ErrorContext(ctx, "Invalid JSON response from teamgamestreakfinder endpoint")
		return nil, fmt.Errorf("invalid JSON response")
	}

	var statsResp StatsResponse
	if err := resp.GetJSON(&statsResp); err != nil {
		c.logger.ErrorContext(ctx, "Failed to unmarshal teamgamestreakfinder response",
			slog.String("error", err.Error()))
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	c.logger.InfoContext(ctx, "Successfully fetched teamgamestreakfinder",
		slog.Int("result_sets_count", len(statsResp.ResultSets)))

	return &statsResp, nil
}
